name: gradely2
description: Your grades on every device.

# The following line prevents the package from being accidentally published to pub.dev using `pub publish`.
publish_to: "none"

version: 1.1.4+14

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  #custom dependencies
  msix: ^3.1.6
  cupertino_icons: ^1.0.4
  appwrite: ^3.0.1
  http: ^0.13.4
  flutter_slidable: ^0.6.0 # Shouldn't be upgraded
  modal_bottom_sheet: ^2.0.0
  flutter_launcher_icons: ^0.9.2
  easy_localization: ^3.0.0
  url_launcher: ^6.0.20
  shared_preferences: ^2.0.13
  syncfusion_flutter_charts: ^19.4.50
  flutter_inapp_purchase: ^5.1.2
  another_flushbar: ^1.10.28
  flutter_svg: ^1.0.3
  package_info_plus: 1.3.0 #Â Wait for upgrade because of windows bug
  universal_io: ^2.0.4
  plausible_analytics: ^0.1.3
  native_context_menu: ^0.2.0+3
  in_app_review: ^2.0.4
  showcaseview: ^1.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to the application
  assets:
    - assets/
    - assets/images/
    - assets/translations/
    - assets/fonts/
  fonts:
    - family: PlayfairDisplay
      fonts:
        - asset: assets/fonts/PlayfairDisplay-ExtraBold.ttf
        - asset: assets/fonts/PlayfairDisplay-Bold.ttf
        - asset: assets/fonts/PlayfairDisplay-Black.ttf

#package to create a msix for windows
#1. flutter build windows
#2. flutter pub run msix:create
msix_config:
  store: true
  display_name: Gradely 2
  publisher_display_name: Elias Schneider
  identity_name: 58500EliasSchneider.Gradely2
  msix_version: 1.1.5.0
  publisher: CN=26AFB924-E2D8-4326-B33D-B268D9E4FB49
  architecture: x64
  capabilities: "internetClient"
  logo_path: assets\images\macOSlogo.png
  start_menu_icon_path: assets\images\macOSlogo.png
  tile_icon_path: assets\images\macOSlogo.png
  icons_background_color: "#ffffff"

#this package generates the app icons for android & ios
#Run this package with: flutter pub run flutter_launcher_icons:main
flutter_icons:
  image_path: "assets/images/gradely2Icon.png"
  ios: true
  android: true
