name: gradely
description: Your grades on every device.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.4.1+16
#Latest builds:
#ios: 1.4.1+5
#MacOS  1.4.1+21
#android: 14

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  appwrite: ^0.7.0
  flutter_slidable: ^0.6.0
  firebase_auth: ^1.3.0
  firebase_core:
  cloud_firestore: ^2.2.1
  flutter_spinkit: 
  modal_bottom_sheet: ^2.0.0
  flutter_launcher_icons:
  introduction_screen: ^2.1.0
  package_info:
  easy_localization: 
  url_launcher:
  firebase_messaging:  10.0.1
  mailer:
  in_app_purchase: ^1.0.6
  flutter_icons:
  page_transition:
  emoji_chooser:
  syncfusion_flutter_charts: ^19.1.66+1
  quiver: ^3.0.1
  flutter_inapp_purchase: ^5.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  image_path: "assets/icon/logo.jpg"
  macos: true
  ios: true
  android: true
  
  # To run: flutter pub run flutter_launcher_icons:main

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/images/
    - assets/icon/
    - assets/translations/


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito-Regular.ttf
        - asset: assets/fonts/Nunito-ExtraBold.ttf
          weight: 700
        

  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
